
# PureChat by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

---

# PureChat version string
# - string
version: "1.4.10-6"

# Set default factions plugin for PureChat
# - FactionsPro / null
default-factions-plugin: FactionsPro

# Enable this if you want to use per-world chat formats / per-world nametags for players
# - true / false
enable-multiworld-chat: false

# Please check if you have all PurePerms groups in your server here

# &0: Black, &1: Dark Blue, &2: Dark Green, &3: Dark Aqua, &4: Dark Red, &5: Dark Purple, &6: Gold, &7: Gray, &8: Dark Gray, &9: Blue
# &a: Green, &b: Aqua, &c: Red, &d: Light Purple, &e: Yellow, &f: White
# &k: Obfuscated, &l: Bold, &m: Strikethrough, &n: Underline, &o: Italic, &r: Reset

# Available PureChat tags: {display_name}, {msg}, {fac_name}, {fac_rank}, {prefix}, {suffix}, {world}
groups:
  Guest:
    chat: '&d{level}&r&l{tier}&r&f{display_name}&r{prefix}&f: &f{msg}'
    nametag: '&a{tier}&r{display_name}&r{prefix}'
    worlds: []
  Admin:
    chat: '&d{level}&r&l{tier}&l&cADMIN&r&b {display_name}&r{prefix}&f: &c{msg}'
    nametag: '&c{tier}&l&cADMIN&r&b {display_name}&r{prefix}'
    worlds: []
  Executive:
    chat: '&d{level}&r&l{tier}&l&0EXECUTIVE&r&a {display_name}&r{prefix}&f: &a{msg}'
    nametag: '&4{tier}&l&0EXECUTIVE&r&a {display_name}&r{prefix}'
    worlds: []
  YouTube:
    chat: '&d{level}&r&l{tier}&l&cYOU&fTUBE&r&c {display_name}&r{prefix}&f: &c{msg}'
    nametag: '&c{tier}&l&cYOU&fTUBE&r&c {display_name}&r{prefix}'
    worlds: []
  Builder:
    chat: '&d{level}&r&l{tier}&l&eBUILDER&r {display_name}&r{prefix}&f: &e{msg}'
    nametag: '&b{tier}&l&eBUILDER&r {display_name}&r{prefix}'
    worlds: []
  Voter:
    nametag: '&e{tier}&l&3VOTER&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&3VOTER&r {display_name}&r{prefix}&f: &f{msg}'
        worlds: []
  Developer:
    nametag: '&5{tier}&l&dDEVELOPER&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&dDEVELOPER&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
  Mod:
    nametag: '&2{tier}&l&9MOD&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&9MOD&r {display_name}&r{prefix}&f: &9{msg}'
        worlds: []
  Designer:
    nametag: '&d{tier}&l&5DESIGNER&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&5DESIGNER&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
  Beta Tester:
    chat: '&d{level}&r&l{tier}&l&3BETA&r {display_name}{prefix}&f: &3{msg}'
    nametag: '&e{tier}&l&3BETA&r {display_name}{prefix}'
        worlds: []
  Supervisor:
    chat: '&d{level}&r&l{tier}&l&dSUPERVISOR&r {display_name}{prefix}&f: &d{msg}'
    nametag: '&1{tier}&l&dSUPERVISOR&r {display_name}{prefix}'
        worlds: []
  Nova:
    nametag: '&d{tier}&l&5NOVA&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&5NOVA&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
  Galaxy:
    nametag: '&d{tier}&l&5GALAXY&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&5GALAXY&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
  Glorious:
    nametag: '&d{tier}&l&5GLORIOUS&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&5GLORIOUS&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
  Nebula:
    nametag: '&d{tier}&l&5NEBULA&r {display_name}&r{prefix}'
    chat: '&d{level}&r&l{tier}&l&5NEBULA&r {display_name}&r{prefix}&f: &d{msg}'
        worlds: []
...